import Head from "next/head";
import "./globals.css";
import { NextUIProviders } from "./providers/nextUIProvider";
import localFont from "@next/font/local";

// const inter = Inter({ subsets: ["latin"] });

const trika = localFont({
  src: [
    {
      path: "../public/fonts/Trika-Regular.ttf",
      weight: "400",
    },
    {
      path: "../public/fonts/Trika-Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-trika",
});

export const metadata = {
  title: "القائمة المستقلة - كلية العلوم",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${trika.variable} font-sans`}>
      <Head>
        <title>MostaqillaSc</title>
        <meta
          name="description"
          content="القائمة المستقلة | كلية العلوم"
          key="desc"
        />
        <meta property="og:title" content="Mostaqilla, Collage of Science" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://mostaqillaesc.com/" />
        <meta property="og:image" content="/thumbnail.png" />
        <meta name="twitter:card" content="/thumbnail.png" />
        <link rel="icon" type="image/png" href="/logo.jpg" />
      </Head>
      <body>
        <NextUIProviders>{children}</NextUIProviders>
      </body>
    </html>
  );
}
